#pragma config(Sensor, dgtl1,  aimLowSensor,   sensorTouch)
#pragma config(Motor,  port2,           rightWeel,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           aimMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           ammoMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port9,           leftWeel,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                             	       - Lokaverkefni Vetur 2016 -                                    *|
|*                                           Ball_Launcher
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
									This program was written for a mobile robot which uses two spinning tires
									to shoot balls in a variety of distances depending on the velocity of the
									gun. The robot is controlled via remote control and the user controls how
									much or if the gun is tilted within a short range and ofcourse where the
									robot will be located and when or if to shoot.
									Buttons:
									Pins:
									Left pin: Forward / backwards
									Right pin: Left / right
									To the right side of the pins:
									Lower button: Pushes the ball towards the spinning wheels.
									Top button: Loads the next ball.
									Left buttons on the front of the remote:
									Upper: Tilt up.
									Lower Tilt down.
									Right buttons on the front of the remote:
									Upper: Start spinning the wheels.
									Lower: Stop spinning the wheels.
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
			Motor Port 2				RightWeel						3-wire									Weel for the gun
			Motor Port 3				RightMotor					3-wire
			Motor Port 4				AimMotor						3-wire									Up and down
			Motor Port 7				AmmoMotor						3-wire									Ammo crate
			Motor Port 8				LeftMotor						3-wire
			Motor Port 9				LeftWeel						3-wire									Weel for the gun
\*-----------------------------------------------------------------------------------------------4246-*/
task main()
{
	int i = 1;
	int x = 0;
	int v = 0;
	while(i ==  1 )
	{                       // Y             X
		motor[leftMotor]  = (vexRT[Ch1] + vexRT[Ch3])/2;
		motor[rightMotor] = (vexRT[Ch1] - vexRT[Ch3])/2;

// Raise or lower aim ---------------------------------------------------
		if(vexRT[Btn5U] == 1)
		{
			motor[aimMotor] = 50;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[aimMotor] = -35;
		}
		else
		{
			motor[aimMotor] = 0;
		}
		// Run the Weels of the gun ----------------------------------------
		if(vexRT[Btn6U] == 1)
		{
			x = 1;
		}
		if(vexRT[Btn6D] == 1)
		{
			x = 0;
		}
		if(x == 1)
		{
			motor[rightWeel] = 127;
			motor[leftWeel] = 127;
		}
		else if(x == 0)
		{
			motor[rightWeel] = 0;
			motor[leftWeel] = 0;
		}
		// Ammo ------------------------------------------------------------
		if(vexRT[Btn8U] == 1)
		{
			v = 1;
		}
		if(vexRT[Btn8D] == 1)
		{
			v = 2;
		}
		if(v == 1)
		{
			motor[ammoMotor] = 35;
			wait1Msec(2000);
			motor[ammoMotor] = -60;
			wait1Msec(1500);
			v = 0;
			
		}
		else if(vexRT[Btn8D] == 1)
		{
			
		}
		else
		{
			motor[ammoMotor] = 0;
		}
		// Emergency stop button ------------------------------------------
		if(vexRT[Btn7U] == 1)
		{
			i = 0;
		}

	}
}
